### ISSUE TITLE
enable localdatastore and use live query, case "Attempted to change an objectId to one that's already known to the Offline Store."

### ISSUE THREAD

**Issue by dilongl** [parse-community/Parse-SDK-Android#770] opened 2017-12-28 14:47 UTC
enable localdatatore
use the liveQuery

call the ParseObject.saveInBackground and use the liveQuery subscribe the same ClassName, 
due to liveQuery receive data then call ParseObject.fromJSON to build a new ParseObject object, case "Attempted to change an objectId to one that's already known to the Offline Store." when the ParseObject.saveInBackground call updateObjectId.

**Comment by Jawnnypoo** [comment] 2018-05-08 05:05
Dupe of #267

**Closed by Jawnnypoo** 2018-05-08 05:06 UTC
