### ISSUE TITLE
Checking for Existence of ParseObject in Collection Always returns false

### ISSUE THREAD

**Issue by WanClem** [parse-community/Parse-SDK-Android#223] opened 2015-10-28 10:21 UTC
Greetings guys,I tried checking for the existence of a ParseObject in a collection in Android(ArrayList
<ParseObject>)but I always get false,this has lead to multiple parseobjects in my collections.I feel like there is the need to override equals(Object o) and compare based on ObjectIds in the ParseObject class.Thanks all.

**Comment by grantland** [comment] 2015-11-09 23:48
This is an interesting subject and something that we've thought about before, but don't really know the best solution for yet as it's not as easy as comparing `ParseObject.getClassName()` and `ParseObject.getObjectId()`.

The problem is that two `ParseObject`s that satisfy those two conditions might be `true`, but the objects might be in a completely different state. One instance can just be a pointer (has only `className` and `objectId`) and the other can have complete data (all fields populated). In addition, one instance can be up-to-date with the server, but another could be outdated. In any of these cases, are they still in fact equal?

Right now the all we know is that the answer isn't "yes", which is why `equals(other)` isn't implemented. This means that all object instances are unique and it's up to the developer to add their own logic to determine equality since different use cases will have different definitions.

I'll leave this marked as an "enhancement" for now in case anyone has a different perspective on how this could be implemented, but we don't have any current plans to change this behavior.

/cc @nlutsenko @richardjrossiii @hallucinogen

**Comment by natario1** [comment] 2017-08-24 18:20
I think we can close this, since there are still no plans. ParseObject subclasses can still implement equals() if they want so..

**Closed by natario1** 2017-08-24 18:20 UTC
Labels: discussion, enhancement
