### ISSUE TITLE
Parse Android SDK exception on Object save 

### ISSUE THREAD

**Issue by RajeshDhalange** [parse-community/Parse-SDK-Android#757] opened 2017-11-08 16:24 UTC
Trying to save object by calling saveInBackground 
Parse version : 1.16.3
Andoid studio : 3.0

com.parse.ParseException: java.lang.RuntimeException: Attempted to change an objectId to one that's already known to the Offline Store.

**Comment by Jawnnypoo** [comment] 2018-05-08 05:05
Dupe of #267

**Closed by Jawnnypoo** 2018-05-08 05:05 UTC
