### ISSUE TITLE
All calls to save() or fetch() on ParseUser and ParseInstallation will freeze if previous call to saveEventually() has failed

### ISSUE THREAD

**Issue by DanGTZ** [parse-community/Parse-SDK-Android#827] opened 2018-05-19 23:08 UTC
After ParseUser.saveEventually() or ParseInstallation.saveEventually() has failed, the sdk seems to be in a corrupted state as all subsequent calls to save() or fetch() on ParseUser and ParseInstallation will freeze. Restarting the app or the device will not solve the issue and only a re-installation of the app allows to save/fetch ParseUser/ParseInstallation again.
This issue occurs with any version of parse-server and any version of Parse-SDK-Android.

## Steps to reproduce the issue on ParseUser (same for ParseInstallation)
1. Log in
2. Delete user session on the server
3. Put new data to user
4. Call user.saveEventually() -> Returns invalid session token error (expected)
5. Close app and relaunch it
6. Put new data to user
7. Call user.save() -> Freeze forever

Note that terminating the app then relaunching it will not change anything : any call to user.save() will freeze (as user.saveInBackground() never completes).
 
## Parse initialization code used

> Parse.setLogLevel(Parse.LOG_LEVEL_VERBOSE);
        Parse.initialize(new Parse.Configuration.Builder(application)
                .applicationId(BuildConfig.PARSE_APP_ID)
                .clientKey(BuildConfig.PARSE_CLIENT_KEY)
                .enableLocalDataStore()
                .server(BuildConfig.SERVER_URL + ":" + BuildConfig.SERVER_PORT + "/parse/")
                .build());

## Standalone app showing the issue

https://github.com/DanGTZ/Parse-Android-SDK-Test

The tests **testSaveEventuallyInstallation** and **testSaveEventuallyUser** passe the first time they are launched, then subsequent launches will freeze on the first save()

https://github.com/DanGTZ/Parse-Android-SDK-Test/blob/master/app/src/androidTest/java/com/perfexpert/parsetest/ParseSaveEventuallyTest.java

## Workaround

This issue occurs after loading invalid data from the cache at step 5. To prevent loading invalid data at startup, clear the ParseUser or ParseInstallation disk cache just after the saveEventually() has failed (step 4). To do so, you can use this gist : https://gist.github.com/DanGTZ/7c95d6fc0bb95d3d7433ab7dc309eeac

**Comment by DanGTZ** [comment] 2018-05-21 15:28
Currently I have users of my app that can't use it because their installation is in this state : any save or fetch in background never returns.
I'm looking for a solution to solve this with an app update, without the need to reinstall the app, in order to prevent data loss.

**Comment by flovilmart** [comment] 2018-05-21 18:49
@DanGTZ this looks quite serious. Are you able to pinpoint the exact reason why this behavior is exhibited?

**Comment by DanGTZ** [comment] 2018-05-22 01:28
@flovilmart it seems that there is a deadlock in the code that manage operations queue for persisted singletons like ParseInstallation and ParseUser, because I'm not able to reproduce this issue with a basic ParseObject, even if I pin the object in LDS.
May be some resources are not released properly when the saveEventually() fails, but my poor knowledge of the sdk code doesn't allows me to tell you more.

**Comment by flovilmart** [comment] 2018-05-22 01:29
@DanGTZ because you're able ton consistently reproduce it, can you perhaps open a failing PR, that exhibit the deadlock? Perhaps plucking a debugger and checking the stack / threads once dead locked can help pinpoint the issue.

**Comment by DanGTZ** [comment] 2018-05-22 01:44
@flovilmart by "failing PR" you mean creating new unit tests in the sdk?
Also to reproduce the issue, one step is to close the current session (call to a custom cloud function "closeAllSession" that I created for my test) : do I need to mock the server to do this in the sdk?

**Comment by flovilmart** [comment] 2018-05-22 01:46
> by "failing PR" you mean creating new unit tests in the sdk?

Yep, I mean a new test that is currently failing without a fix.

> do I need to mock the server to do this in the sdk?

Most probably, adding a mock would be the way to go as we never run edge to edge tests with a live server for this SDK IIUC.

**Comment by DanGTZ** [comment] 2018-05-29 20:49
@flovilmart I'm not able to reproduce this issue with unit tests #831 
After more integration testing in my own app, it seems that the freeze occurs only after relaunching the app after the saveEventually() fails.

**Comment by flovilmart** [comment] 2018-05-29 20:50
Ok, so that means that the full app is in an invalid state which is quite bad as we have a persistent issue.

**Comment by DanGTZ** [comment] 2018-05-29 20:59
Yes, and now I have to take my time to prepare a publication for my users to explain them the only solution to the problem is to reinstall the app and then lost all their local data (pinned in localdatastore)  :-(

**Comment by flovilmart** [comment] 2018-05-29 21:06
Nah, we can do better I believe no? If we find the soUrce of the deadlock, we can ensure that at next restart everything is back on track

**Comment by DanGTZ** [comment] 2018-05-29 21:17
That's what I was trying to do.

The exact async method that doesn't return is this one :
https://github.com/parse-community/Parse-SDK-Android/blob/master/Parse/src/main/java/com/parse/ParseObject.java#L1604

**Comment by DanGTZ** [comment] 2018-05-29 22:36
@flovilmart here is a standalone app showing the issue :

https://github.com/DanGTZ/Parse-Android-SDK-Test

The tests **testSaveEventuallyInstallation** and **testSaveEventuallyUser** passe the first time they are launched, then subsequent launches will freeze on the first save()

https://github.com/DanGTZ/Parse-Android-SDK-Test/blob/master/app/src/androidTest/java/com/perfexpert/parsetest/ParseSaveEventuallyTest.java

**Comment by flovilmart** [comment] 2018-05-29 22:41
@Jawnnypoo and @rogerhu , is that something you guys you could have a look at?

**Comment by DanGTZ** [comment] 2018-06-01 19:40
Here is the cloud code that is needed for this test :
Parse.Cloud.define("closeAllSessions", function(request, response) {
  if (!request.user) {
    response.error("A user must be logged in");
  } else {
    var sessionQuery = new Parse.Query(Session);
    sessionQuery.equalTo('user', request.user);
    sessionQuery.find({
      useMasterKey: true
    }).then(function(sessions) {
      console.log(sessions.length + " sessions will be closed");
      return Parse.Object.destroyAll(sessions, {
        useMasterKey: true
      });
    }).then(function() {
      response.success();
    }, function(error) {
      response.error(error.message);
    });
  }
});

**Comment by rogerhu** [comment] 2018-06-03 00:00
Thanks for the repro -- I see the same thing.   Note I had to change your code to be ```new Parse.Query(Parse.Session);``` to get things to work.

**Comment by DanGTZ** [comment] 2018-06-03 17:16
@rogerhu sorry forgot to add this line before the function : `var Session = Parse.Object.extend('_Session'); `

**Comment by DanGTZ** [comment] 2018-06-05 23:56
More info, once the saveEventually has failed :

- The problem occurs only after relaunching the app

- The problem doesn't occur if there is a successful saving of the object (User or Installation) before relaunching the app.

- The problem doesn't occur if LDS is not enabled

I guess something wrong is persisted in LDS when saveEventually fails. Then after relaunch, the wrong data is loaded from LDS and make any subsequent save deadlocking. If the app is not relaunched, user logs in and save the object, the wrong data is removed from LDS, due to successful saving, and the problem never occurs. I think this is the most likely hypothesis.

**Comment by DanGTZ** [comment] 2018-06-10 20:07
This issue occurs after loading invalid data from the cache at step 5. To prevent loading invalid data at startup, clear the ParseUser or ParseInstallation disk cache just after the saveEventually() has failed (step 4). To do so, you can use this gist : https://gist.github.com/DanGTZ/7c95d6fc0bb95d3d7433ab7dc309eeac

I've also updated my test app so you can see the impact of clearing cache : https://github.com/DanGTZ/Parse-Android-SDK-Test

**Comment by Jawnnypoo** [comment] 2018-07-20 05:15
Fixed with #831

**Closed by Jawnnypoo** 2018-07-20 05:15 UTC
