### ISSUE TITLE
When signing up a subclass of ParseUser, signUpInBackground never completes

### ISSUE THREAD

**Issue by aphexcx** [parse-community/Parse-SDK-Android#450] opened 2016-05-07 03:46 UTC
Please see this StackOverflow issue I opened:

http://stackoverflow.com/questions/37039076/when-signing-up-a-parseuser-created-with-parseuser-create-user-signupinback

Repro steps: Create a subclass of ParseUser and register it. Then instantiate it and call `signUpInBackground`. The `done()` callback is never triggered for successful signups.

**Comment by afotest** [comment] 2016-05-28 09:53
after signupinbackground is called it send request for three times and then show below exception

05-28 15:17:23.548 30932-30932/com.parse.starter W/System.err: com.parse.ParseRequest$ParseRequestException: i/o failure
05-28 15:17:23.549 30932-30932/com.parse.starter W/System.err:     at com.parse.ParseRequest.newTemporaryException(ParseRequest.java:290)
05-28 15:17:23.549 30932-30932/com.parse.starter W/System.err:     at com.parse.ParseRequest$2.then(ParseRequest.java:145)
05-28 15:17:23.549 30932-30932/com.parse.starter W/System.err:     at com.parse.ParseRequest$2.then(ParseRequest.java:139)
05-28 15:17:23.549 30932-30932/com.parse.starter W/System.err:     at bolts.Task$15.run(Task.java:917)
05-28 15:17:23.549 30932-30932/com.parse.starter W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-28 15:17:23.549 30932-30932/com.parse.starter W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-28 15:17:23.551 30932-30932/com.parse.starter W/System.err:     at java.lang.Thread.run(Thread.java:818)
05-28 15:17:23.551 30932-30932/com.parse.starter W/System.err: Caused by: java.net.SocketTimeoutException
05-28 15:17:23.554 30932-30932/com.parse.starter W/System.err:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:562)
05-28 15:17:23.554 30932-30932/com.parse.starter W/System.err:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:47)
05-28 15:17:23.556 30932-30932/com.parse.starter W/System.err:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:259)
05-28 15:17:23.556 30932-30932/com.parse.starter W/System.err:     at com.android.okio.Okio$2.read(Okio.java:113)
05-28 15:17:23.556 30932-30932/com.parse.starter W/System.err:     at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:147)
05-28 15:17:23.556 30932-30932/com.parse.starter W/System.err:     at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:94)
05-28 15:17:23.562 30932-30932/com.parse.starter W/System.err:     at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
05-28 15:17:23.562 30932-30932/com.parse.starter W/System.err:     at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
05-28 15:17:23.564 30932-30932/com.parse.starter W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:636)
05-28 15:17:23.564 30932-30932/com.parse.starter W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:398)
05-28 15:17:23.568 30932-30932/com.parse.starter W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:342)
05-28 15:17:23.568 30932-30932/com.parse.starter W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:520)
05-28 15:17:23.568 30932-30932/com.parse.starter W/System.err:     at com.parse.ParseURLConnectionHttpClient.getResponse(ParseURLConnectionHttpClient.java:103)
05-28 15:17:23.569 30932-30932/com.parse.starter W/System.err:     at com.parse.ParseURLConnectionHttpClient.executeInternal(ParseURLConnectionHttpClient.java:54)
05-28 15:17:23.570 30932-30932/com.parse.starter W/System.err:     at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:158)
05-28 15:17:23.570 30932-30932/com.parse.starter W/System.err:     at com.parse.ParsePlugins$1.intercept(ParsePlugins.java:115)
05-28 15:17:23.570 30932-30932/com.parse.starter W/System.err:     at com.parse.ParseHttpClient$ParseNetworkInterceptorChain.proceed(ParseHttpClient.java:147)
05-28 15:17:23.572 30932-30932/com.parse.starter W/System.err:     at com.parse.ParseHttpClient.execute(ParseHttpClient.java:122)
05-28 15:17:23.572 30932-30932/com.parse.starter W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:136)
05-28 15:17:23.572 30932-30932/com.parse.starter W/System.err:     at com.parse.ParseRequest$3.then(ParseRequest.java:133)
05-28 15:17:23.573 30932-30932/com.parse.starter W/System.err:     at bolts.Task$15.run(Task.java:917)
05-28 15:17:23.573 30932-30932/com.parse.starter W/System.err:     at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
05-28 15:17:23.574 30932-30932/com.parse.starter W/System.err:     at bolts.Task.completeAfterTask(Task.java:908)
05-28 15:17:23.574 30932-30932/com.parse.starter W/System.err:     at bolts.Task.continueWithTask(Task.java:715)
05-28 15:17:23.574 30932-30932/com.parse.starter W/System.err:     at bolts.Task.continueWithTask(Task.java:726)
05-28 15:17:23.574 30932-30932/com.parse.starter W/System.err:     at bolts.Task$13.then(Task.java:818)
05-28 15:17:23.574 30932-30932/com.parse.starter W/System.err:     at bolts.Task$13.then(Task.java:806)

**Comment by Tom-Fox1** [comment] 2019-04-04 19:03
Closing this as no one has reported this issue recently, and we don't have the resources to investigate these historic reports.

Please ask me to reopen if you experience this issue in the latest version of this SDK.

**Closed by Tom-Fox1** 2019-04-04 19:03 UTC
