### ISSUE TITLE
Cloud function fails on Android 12

### ISSUE THREAD

**Issue by buzmax** [parse-community/Parse-SDK-Android#1145] opened 2021-11-25 12:40 UTC
When I try to call cloud function (ParseCloud.callFunction...) on android 12 I get this exception: 
 
❌ java.lang.IllegalArgumentException: com.onstruct.android.uat: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

**Comment by mtrezza** [comment] 2021-11-25 12:57
@L3K0V Side note, would it make sense / be possible to add various Android CI environments, like we run our Parse Server CI in various Node.js environments?

**Comment by L3K0V** [comment] 2021-11-25 13:04
Make sense @mtrezza, but some tests must be added/updated. 
I hope @buzmax uses and old version, as `FLAG_IMMUTABLE` was introduced what, like week ago...

**Comment by L3K0V** [comment] 2021-11-30 10:02
@buzmax can you confirm that this happens on the latest version of the SDK?

Can you share a bit more detailed log, not sure how ParseCloud is related with pending intents.

**Comment by mtrezza** [comment] 2022-04-27 13:00
I've pinned this issue; in case there is really an issue with Android 12, we need to address this urgently.

**Comment by mman** [comment] 2022-04-27 14:53
@buzmax We need more details. The error you are showing does not relate at all to calling cloud functions via Parse SDK. Please post a stack trace or snippet of code what you are doing around `ParseCloud.callFunction` and we can investigate.

**Comment by mtrezza** [comment] 2022-04-27 20:45
I think the way to try to replicate this is to have an Android app target Android 12 and try using the Parse SDK like calling a Cloud Code function.

**Comment by mman** [comment] 2022-04-28 07:27
@mtrezza I have android sdk in production using cloud functions, no problems on any android

**Comment by mman** [comment] 2022-04-28 07:33
@mtrezza To be precise I am now targeting API level 31 (Android 12) with `minSdkVersion` stuck on API level 19 (Android 4.4), thus still using Parse-SDK-Android version 2.1.0. And can not replicate the issue in any way.

```
    compileSdkVersion=31
    targetSdkVersion=31
    minSdkVersion=19
```

Need more data for this.

**Comment by mtrezza** [comment] 2022-04-28 07:39
Thanks @mman that's a good indication at least that you cannot replicate.

**Comment by mman** [comment] 2022-04-28 07:47
@mtrezza I will do some more investigation next week when I get a chance, but for now I think this is unrelated to Parse Android SDK.

**Comment by mtrezza** [comment] 2022-04-28 07:49
I guess one point of investigation could be to look whether the SDKs actually uses any PendingIntent.

**Comment by SantosVithor** [comment] 2022-05-06 21:03
I'm in an old project that was using these libs for parse: 
```
//Parse
    implementation 'com.parse:parse-android:1.17.3'
    implementation 'com.parse:parse-fcm-android:1.17.3'
    implementation "com.github.yongjhih.RxParse:rxparse2:2.1.0"
```

But because I had to update to sdk 31, I had this issue that @buzmax pointed out. Solved after updating gradle, kotlin and other stuff. But when I receive a push notification, the app crashes (on the super line):

```
override fun onPushReceive(context: Context, intent: Intent) {
        super.onPushReceive(context, intent)
        parseIncomingIntent(intent, context, false)
}
```

I don't understand quite yet these "advanced" concepts, but, from where I'm standing, it looks like those old libs use pending intents somewhere. Right now, I'm struggling to properly update without causing this crash. One other thing is that I changed my old libs for the "new" ones: 

```
    implementation "com.github.parse-community.Parse-SDK-Android:parse:2.0.6"
    implementation "com.github.parse-community.Parse-SDK-Android:fcm:2.0.6"
    implementation "com.github.parse-community.Parse-SDK-Android:rxjava:2.0.6"
    implementation "com.github.parse-community.Parse-SDK-Android:ktx:2.0.6"
    implementation "com.github.parse-community.Parse-SDK-Android:coroutines:2.0.6"
```
And that solved this pending intent problem, but I'm having some other bugs related to some old custom code related to `ParseObsevalbe.callFunction` not existing in these new libs.

I thought that the problem seemed similar to mine, so I wanted to make it clear. I guess that's why this problem is in the Parse SDK issue list.

**Comment by mtrezza** [comment] 2022-05-06 21:21
Thanks, please let us know if you discover more.

**Comment by mtrezza** [comment] 2022-05-21 18:25
I tried it out with an old Parse Android SDK 1.24.2, targetSdkVersion 31, compileSdkVersion 31 on Android API 31 and was not able to reproduce the issue even with that old SDK version. I was able to reproduce this however by creating a `PendingIntent` without any mutability flag. 

Was is really necessary here is a full stack trace instead of just the error message. So we can know whether this comes from custom code or the Parse Android SDK, and from where inside the SDK exactly.

I am closing this for now until someone can at least provide a complete stack trace that verifies that this is caused inside the SDK.

**Closed by mtrezza** 2022-05-21 18:25 UTC
Labels: type:bug, bounty:$100
