### ISSUE TITLE
UncaughtException: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/Collection;Ljava/util/Collection;Lcom/facebook/AccessTokenSource;Ljava/util/Date;Ljava/util/Date;)V in class Lcom/facebook/AccessToken; or its super classes (declaration of 'com.facebook.AccessToken' 

### ISSUE THREAD

**Issue by hoffergg** [parse-community/Parse-SDK-Android#908] opened 2018-11-14 14:38 UTC
I use facebook to login and the call ParseUser.logOutInBackground to log out and meet this error:

`UncaughtException: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/Collection;Ljava/util/Collection;Lcom/facebook/AccessTokenSource;Ljava/util/Date;Ljava/util/Date;)V in class Lcom/facebook/AccessToken; or its super classes (declaration of 'com.facebook.AccessToken' `

parse:parsefacebookutils is:
com.parse:parsefacebookutils-v4-android:1.10.3@aar

**Comment by Jawnnypoo** [comment] 2018-11-14 15:33
Dupe of https://github.com/parse-community/ParseFacebookUtils-Android/issues/46

**Closed by Jawnnypoo** 2018-11-14 15:33 UTC
